# Generated by Django 6.0.5 on 2026-05-24 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('blog', 'Blog Post'), ('youtube', 'YouTube Script'), ('instagram', 'Instagram Caption'), ('linkedin', 'LinkedIn Article'), ('email', 'Email Newsletter'), ('twitter', 'Twitter/X Thread'), ('podcast', 'Podcast Outline')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('target_audience', models.CharField(blank=True, max_length=200)),
                ('word_count', models.PositiveIntegerField(default=500)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('funny', 'Funny'), ('inspirational', 'Inspirational'), ('persuasive', 'Persuasive')], default='professional', max_length=30)),
                ('content', models.TextField()),
                ('seo_score', models.IntegerField(blank=True, null=True)),
                ('seo_meta_title', models.CharField(blank=True, max_length=70)),
                ('seo_meta_description', models.CharField(blank=True, max_length=160)),
                ('seo_keywords_suggested', models.TextField(blank=True)),
                ('readability_score', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('grammar_notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='generator.contentproject')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('draft', 'Draft'), ('in_progress', 'In Progress'), ('published', 'Published')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_slots', to='generator.generatedcontent')),
            ],
            options={
                'verbose_name_plural': 'Content calendar entries',
                'ordering': ['date'],
            },
        ),
    ]
